
title: kikata
email: info@kikata.com
description: >- # this means to ignore newlines until "baseurl:"
  Our solutions connect seamlessly across various networks, ensuring uninterrupted access to essential services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kikatalabs.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings

theme: cayman
remote-theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

